# Generated by Django 2.0.5 on 2018-06-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_auto_20180619_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='describtion',
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='std',
            field=models.TextField(default=''),
        ),
    ]
