# Generated by Django 2.0.5 on 2018-06-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0004_auto_20180620_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(default='')),
                ('problem_count', models.IntegerField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('problem_set', models.ManyToManyField(to='oj.Problem')),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='source',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contest',
            name='submission_set',
            field=models.ManyToManyField(to='oj.Submission'),
        ),
    ]
