# Generated by Django 2.0.5 on 2018-06-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0005_auto_20180621_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='std_language',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('java', 'Java')], default='c', max_length=5),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('java', 'Java')], default='c', max_length=5),
        ),
    ]
