# Generated by Django 2.0.5 on 2018-06-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0006_auto_20180621_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='judge_time',
            new_name='submit_time',
        ),
        migrations.AlterField(
            model_name='problem',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
		migrations.RunSQL('alter table oj_problem auto_increment=1000'),
    ]
